# Generated by Django 4.2.11 on 2025-01-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
