# Generated by Django 5.1.4 on 2025-01-21 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_member_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(max_length=1000000, unique=True)),
                ('cat_name', models.CharField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField(max_length=100000, unique=True)),
                ('prod_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=100000)),
                ('qty', models.IntegerField(max_length=1000)),
                ('order_id', models.IntegerField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(max_length=1000000, unique=True)),
                ('cat_name', models.CharField(max_length=255, unique=True)),
                ('prod_id', models.IntegerField(max_length=100000, unique=True)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_desc', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=100000)),
                ('stock_qty', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pwd_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=1000000)),
                ('creation_date', models.DateTimeField()),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
