# Generated by Django 5.1.4 on 2025-01-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_category_order_product_pwd_history_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='prod_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pwd_history',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
