# Generated by Django 4.2.11 on 2025-01-24 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_category_cat_id_alter_member_mobile_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member')),
            ],
        ),
        migrations.DeleteModel(
            name='pwd_history',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prod_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_name',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
