# Generated by Django 4.2.11 on 2025-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pwdhistory_delete_pwd_history_remove_order_prod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='./images/template.png', upload_to='./images'),
        ),
    ]
