# Generated by Django 4.2.11 on 2025-01-24 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_category_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
