# Generated by Django 4.2.11 on 2025-01-24 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_member_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(6666666666), django.core.validators.MaxLengthValidator(9999999999)]),
        ),
    ]
