# Generated by Django 4.2.11 on 2025-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_member_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='./images/template.png', upload_to='./images'),
        ),
    ]
