# Generated by Django 5.1.4 on 2025-01-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_order_id_alter_category_cat_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
