# Generated by Django 5.1.4 on 2025-01-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_product_order_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
