# Generated by Django 5.1.4 on 2025-01-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_category_cat_img_alter_product_product_img'),
        ('users', '0019_order'),
    ]

    operations = [
    ]
