# Generated by Django 5.1.4 on 2025-02-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_price_order_order_total_remove_order_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
