# Generated by Django 5.1.4 on 2025-02-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='product_name',
        ),
    ]
