# Generated by Django 5.1.4 on 2025-02-01 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_prod_desc_product_product_desc_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='no address provided', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='user123', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(6666666666), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
    ]
