# Generated by Django 5.1.4 on 2025-02-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_product_stock_qty_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
    ]
